# Испольуем особую переменную с перечислением доверенных прокси
map $remote_addr $trusted_x_forwarded_for {
    172.28.0.11    $proxy_add_x_forwarded_for;
    172.28.0.12    $proxy_add_x_forwarded_for;
    default        $remote_addr;
}

server {
    listen 80;
    # Обработчик специально для php-fpm. Для других типов бекендов обработка должна делаться иначе
    location / {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param HTTP_X_FORWARDED_FOR  $trusted_x_forwarded_for;
        fastcgi_pass php:9000;
    }

}